package com.super_market.model;

public enum Permission {
    // Common for all users
    CHANGE_PASSWORD,

    // Admin permissions
    CREATE_EMPLOYEE, DELETE_EMPLOYEE, UPDATE_EMPLOYEE, READ_ALL_EMPLOYEES,
    CREATE_PRODUCT, DELETE_PRODUCT, UPDATE_PRODUCT, READ_ALL_PRODUCTS, READ_SECTION_PRODUCTS,
    CREATE_SECTION, DELETE_SECTION, UPDATE_SECTION, READ_ALL_SECTIONS,
    CREATE_RECEIPT, DELETE_RECEIPT, READ_ALL_RECEIPTS, READ_CASHIER_RECEIPTS, READ_MY_RECEIPTS, READ_RECEIPT,

    // Cashier permissions
    CASHIER_CREATE_RECEIPT, CASHIER_DELETE_RECEIPT, CASHIER_READ_ALL_RECEIPTS, CASHIER_READ_MY_RECEIPTS, CASHIER_READ_RECEIPT,

    // Storekeeper permissions
    STOREKEEPER_CREATE_PRODUCT, STOREKEEPER_DELETE_PRODUCT, STOREKEEPER_UPDATE_PRODUCT, STOREKEEPER_READ_ALL_PRODUCTS, STOREKEEPER_READ_SECTION_PRODUCTS,
    STOREKEEPER_CREATE_SECTION, STOREKEEPER_DELETE_SECTION, STOREKEEPER_UPDATE_SECTION, STOREKEEPER_READ_ALL_SECTIONS
}
